### ISSUE TITLE
Read Time Out

### ISSUE THREAD

**Issue by tumbelin** [epayco/epayco-android#1]
Hola @prismaymedia @epayco , estoy teniendo varios problemas con el tema del tiempo de respuesta, dado que por defecto con la clase que ustedes utilizan para la conexión (AsyncHttpClient) el tiempo es de 10 segundos (public static final int DEFAULT_SOCKET_TIMEOUT = 10 * 1000;), y tengo entendido que los tiempos maximos con ustedes son hasta de 180 segundos. 

Que tal si utilizan el metodo `setResponseTimeout(int value)` de la clase y le asignan un tiempo mas alto de respuesta.

**Comment by devepayco** [comment]
Hola @tumbelin este Issue ya se encuentra corregido, por favor descargar nuevamente la librería, agradecemos amablemente su reporte
